### ISSUE TITLE
Exporting a model that requires prompts (for example, FastSAM)

### ISSUE THREAD

**Issue by ccharp** [ultralytics/yolo-ios-app#49]
Hello, friends. First, thank you for making this repository publicly available. 

I'm trying to integrate FastSAM into the template you have established here. However, I'm not sure how to handle FastSAM's prompts, e.g. a bounding box or point.

I don't see anything useful in `FastSAM-s`'s `FastSAM_sINput` that was generated by xcode, which is where I expected to see some other features declared beside "image". 

```
@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
class FastSAM_sInput : MLFeatureProvider {

    /// image as color (kCVPixelFormatType_32BGRA) image buffer, 640 pixels wide by 640 pixels high
    var image: CVPixelBuffer

    var featureNames: Set<String> {
        get {
            return ["image"]
        }
    }
    
    func featureValue(for featureName: String) -> MLFeatureValue? {
        if (featureName == "image") {
            return MLFeatureValue(pixelBuffer: image)
        }
        return nil
    }
    
    init(image: CVPixelBuffer) {
        self.image = image
    }

    convenience init(imageWith image: CGImage) throws {
        self.init(image: try MLFeatureValue(cgImage: image, pixelsWide: 640, pixelsHigh: 640, pixelFormatType: kCVPixelFormatType_32ARGB, options: nil).imageBufferValue!)
    }

    convenience init(imageAt image: URL) throws {
        self.init(image: try MLFeatureValue(imageAt: image, pixelsWide: 640, pixelsHigh: 640, pixelFormatType: kCVPixelFormatType_32ARGB, options: nil).imageBufferValue!)
    }

    func setImage(with image: CGImage) throws  {
        self.image = try MLFeatureValue(cgImage: image, pixelsWide: 640, pixelsHigh: 640, pixelFormatType: kCVPixelFormatType_32ARGB, options: nil).imageBufferValue!
    }

    func setImage(with image: URL) throws  {
        self.image = try MLFeatureValue(imageAt: image, pixelsWide: 640, pixelsHigh: 640, pixelFormatType: kCVPixelFormatType_32ARGB, options: nil).imageBufferValue!
    }

}
```

Here's how I'm exporting the model to CoreML:
```
from ultralytics import FastSAM

model = FastSAM("FastSAM-s.pt")
model.export(format="coreml", int8=True, nms=True, imgsz=1024)
```

**Comment by ccharp** [comment]
I found something that might be helpful, but it raises another question. See the line [here](https://github.com/CASIA-IVA-Lab/FastSAM/blob/b4ed20c2fed75eadc5aa7d8b09fedd137b873b52/fastsam/model.py#L76) in FastSAM's github repository.

```
    @smart_inference_mode()
    def export(self, **kwargs):
        """
        Export model.

        Args:
            **kwargs : Any other args accepted by the predictors. To see all args check 'configuration' section in docs
        """
```
What is "'configuration' section in docs" referring to?

**Comment by pderrenger** [comment]
@ccharp hello,

Thank you for your question and for your interest in integrating FastSAM into your project! Let's address your concerns step-by-step.

### Handling Prompts in FastSAM

FastSAM's prompts (e.g., bounding boxes, points) are indeed crucial for its functionality. When exporting the model to CoreML, these prompts need to be handled appropriately. The CoreML model you generated seems to only accept an image input, which is why you don't see the additional features for prompts.

### Exporting FastSAM with Prompts

To ensure that prompts are included when exporting the model, you might need to customize the export process. Unfortunately, the current export functionality might not directly support prompt-based inputs out-of-the-box. However, you can work around this by using the FastSAMPredictor class for inference, which allows you to handle prompts after the initial segmentation.

Here's an example of how you can use the FastSAMPredictor for prompt-based inference:

```python
from ultralytics.models.fastsam import FastSAMPredictor

# Create FastSAMPredictor
overrides = dict(conf=0.25, task="segment", mode="predict", model="FastSAM-s.pt", save=False, imgsz=1024)
predictor = FastSAMPredictor(overrides=overrides)

# Segment everything
everything_results = predictor("path/to/image.jpg")

# Prompt inference
bbox_results = predictor.prompt(everything_results, bboxes=[[200, 200, 300, 300]])
point_results = predictor.prompt(everything_results, points=[200, 200])
text_results = predictor.prompt(everything_results, texts="a photo of a dog")
```

### Clarification on the 'configuration' Section in Docs

The line you referred to in the FastSAM repository mentions a 'configuration' section in the documentation. This likely refers to the section where all configurable parameters for the model and its predictors are documented. Unfortunately, the exact location of this section isn't specified in the snippet you provided.

To find this information, I recommend checking the official FastSAM documentation or the README file in the repository. If the documentation is unclear or incomplete, you might want to reach out to the maintainers of the FastSAM repository for further clarification.

### Ensuring Latest Versions

If you encounter any issues during this process, please ensure that you are using the latest versions of the Ultralytics and FastSAM packages. This can help resolve any bugs or issues that might have been addressed in recent updates.

```bash
pip install --upgrade ultralytics
pip install --upgrade fastsam
```

I hope this helps! If you have any further questions or run into any issues, feel free to ask. The Ultralytics community and team are here to support you. 😊

**Comment by ccharp** [comment]
Thank you for the thorough reply, @pderrenger . 

It looks like I'll have to implement predictor logic in Swift. 

For posterity, I went ahead and opened a ticket with FastSAM proper: https://github.com/CASIA-IVA-Lab/FastSAM/issues/241

Since this ticket is out of your purview, I'm going to go ahead and close. Thanks again.

**Comment by pderrenger** [comment]
Hello @ccharp,

Thank you for the update and for taking the initiative to open a ticket with the FastSAM repository. Implementing the predictor logic in Swift sounds like a solid approach to handle the prompts effectively.

If you encounter any further questions or need additional assistance with integrating FastSAM or any other Ultralytics models, feel free to reach out. We're here to help! 😊

Best of luck with your project, and thank you for being a part of the YOLO community!

Warm
