### ISSUE TITLE
Where can I find YOLO11 Models?

### ISSUE THREAD

**Issue by zumisio** [ultralytics/yolo-ios-app#70]
https://github.com/ultralytics/yolo-ios-app?tab=readme-ov-file

Add YOLO11 Models to the Project:

Export CoreML INT8 models using the ultralytics Python package (with pip install ultralytics), or download them from our [GitHub release assets](https://github.com/ultralytics/yolo-ios-app/releases). You should have 5 YOLO11 models in total. Place these in the YOLO/Models directory as seen in the Xcode screenshot below.

**↑The model of the asset is the 8 series.Please change to 11 series
Also, is it still easier to develop with UI Kit (storyboard) instead of swift ui?
When changing from model 8 to model 11 this time, I expected a change from UI Kit (storyboard) to Swift UI...**

**Comment by UltralyticsAssistant** [comment]
👋 Hello @zumisio, thank you for submitting a `ultralytics/yolo-ios-app` 🚀 Issue. To help us address your concern efficiently, please ensure you've provided the following information:

1. For bug reports:
   - A clear and concise description of the bug
   - A minimum reproducible example (MRE)[https://docs.ultralytics.com/help/minimum_reproducible_example/] that demonstrates the issue
   - Your environment details (OS, Python version, package versions, etc.)
   - Expected behavior vs. actual behavior
   - Any error messages or logs related to the issue

2. For feature requests:
   - A clear and concise description of the proposed feature
   - The problem this feature would solve
   - Any alternative solutions you've considered

3. For questions:
   - Provide as much context as possible about your question
   - Specify which changes or expectations you have regarding the migration from the YOLOv8 series to YOLOv11 models (if applicable)
   - Include any insights on whether you’ve reviewed [our documentation](https://docs.ultralytics.com) as it relates to CoreML INT8 exports or model usage
   - Mention your experiences if you’ve already tested UI Kit vs SwiftUI, and your reasons for considering moving between the two

Please also confirm the specific scenario you are working on and review our [existing issues](https://github.com/ultralytics/yolo-ios-app/issues) to ensure there are no duplicates. If there are specific changes or clarifications to the implementation of YOLOv11 models (or UI frameworks) you'd love to see added, let us know in detail!

Thank you for helping us improve the project! 🔥 An Ultralytics engineer will review and assist you shortly. 😊

**Comment by pderrenger** [comment]
@zumisio thank you for your question! To access YOLO11 models, you can export them using the `ultralytics` Python package with the `export` functionality, or check for updated release assets on the [Ultralytics GitHub releases page](https://github.com/ultralytics/yolo-ios-app/releases). Ensure you place the exported models in the proper directory, as outlined in the project documentation. Regarding UI Kit vs. SwiftUI, both can be used effectively, but the choice depends on your app's architecture and your team's familiarity with these frameworks. SwiftUI offers modern declarative syntax, while UI Kit might remain easier for projects with existing storyboard implementations.

**Comment by zumisio** [comment]
Thanks for answering my question！
![スクリーンショット 2024-12-11 9 32 28](https://github.com/user-attachments/assets/17df7455-e7e6-459a-ac73-44c702f04a8c)
↑**The model that is the asset here is the 8 series. Updates also stopped in February. Am I looking at the wrong page?**

**Comment by pderrenger** [comment]
@zumisio you're welcome! The YOLOv8 models currently available on that page were the latest at the time updates ceased in February. For YOLO11 models, please ensure you're using the latest `ultralytics` package (`pip install --upgrade ultralytics`) and refer to the [Ultralytics CoreML documentation](https://docs.ultralytics.com/integrations/coreml/) or the [iOS App release assets](https://github.com/ultralytics/yolo-ios-app/releases) for updated model files. Let me know if you need further clarification!

**Comment by glenn-jocher** [comment]
@zumisio thank you for your patience! We've exported all YOLO11 models to CoreML now and attached them to the latest v8.3.0 release assets here: https://github.com/ultralytics/yolo-ios-app/releases/tag/v8.3.0

<img width="1548" alt="Screenshot 2024-12-13 at 00 00 39" src="https://github.com/user-attachments/assets/7ff2bf38-bb88-469a-91bc-0f47e2a59a91" />

**Comment by dev-xdyang** [comment]
> @zumisio thank you for your patience! We've exported all YOLO11 models to CoreML now and attached them to the latest v8.3.0 release assets here: https://github.com/ultralytics/yolo-ios-app/releases/tag/v8.3.0
> 
> <img alt="Screenshot 2024-12-13 at 00 00 39" width="1548" src="https://private-user-images.githubusercontent.com/26833433/395355613-7ff2bf38-bb88-469a-91bc-0f47e2a59a91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MjY1ODYsIm5iZiI6MTczNDQyNjI4NiwicGF0aCI6Ii8yNjgzMzQzMy8zOTUzNTU2MTMtN2ZmMmJmMzgtYmI4OC00NjlhLTkxYmMtMGY0N2UyYTU5YTkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDA5MDQ0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxNzYyOTE1M2Y0YzRhYTdmYjMwM2E3NzcxYmM5ZWVlOGU2NWZiZDZjODZkMzNmY2FlNDBkNmVlZTE5OTU5NmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5U3uYRbh3wWeHCCbshTd9-9dUPVwpa4pSuIYVaq6biw">


When I use the yolo11_coreml_models.zip in Release, I encounter a crash "Class labels are missing from the model description"

**Comment by john-rocky** [comment]
@dev-xdyang
Thank you for letting us know.
We're sorry, nms had not been added to the model in the release assets.
We've updated the release assets and re-uploaded the model with nms added. We apologize for the inconvenience, but please try downloading again.

[https://github.com/ultralytics/yolo-ios-app/releases/tag/v8.3.0](https://github.com/ultralytics/yolo-ios-app/releases/tag/v8.3.0)](https://github.com/ultralytics/yolo-ios-app/releases/tag/v8.3.0%5D(https://github.com/ultralytics/yolo-ios-app/releases/tag/v8.3.0))
