### ISSUE TITLE
Detections are not good if I hold my phone in landscape mode.

### ISSUE THREAD

**Issue by chiman-09** [ultralytics/yolo-ios-app#73]
I am able to get bounded boxes for all objects present in real-time only when the phone is held in portrait mode. If i rotate the phone the bounding boxes vanishes

**Comment by UltralyticsAssistant** [comment]
👋 Hello @chiman-09, thank you for submitting a `ultralytics/yolo-ios-app` 🚀 Issue. To help us address your concern efficiently, please provide the following information:

1. For bug reports:
   - A clear and concise description of the bug (e.g., does this only happen in certain orientations or with certain objects?)
   - A minimum reproducible example (MRE)[https://docs.ultralytics.com/help/minimum_reproducible_example/] that demonstrates the issue (e.g., sample code or steps to replicate the bug)
   - Your device details (iOS version, device model)
   - App configuration or settings, if any were changed
   - Expected behavior vs. actual behavior (e.g., does detection completely stop or does it behave differently?)
   - Any error messages, logs, screenshots, or screen recordings that can help us troubleshoot the issue 📸

2. For general context:
   - Describe any research or steps you've already taken to investigate the problem
   - If this could be related to specific device permissions (e.g., camera rotation handling) or system configurations, please let us know.

Please make sure to search existing issues to see if this problem has already been reported. If there's any additional information you’d like to share, don't hesitate to comment on this issue.

🔧 An Ultralytics engineer will review and assist with your issue as soon as possible. Thank you for helping us improve our projects! 😊

**Comment by pderrenger** [comment]
@chiman-09 it seems like the issue might be related to inconsistent orientation or preprocessing of the input frames in landscape mode. Please ensure that your input frames are correctly oriented before passing them to the model. You can use OpenCV's `cv2.rotate` or similar methods to standardize the frame orientation. If the issue persists, verify with the latest version of the Ultralytics package and share more details if needed.
