### ISSUE TITLE
 cannot find 'yolov8m

### ISSUE THREAD

**Issue by pascal-maker** [ultralytics/yolo-ios-app#9]
Tried running the project after adding the models to the project and received these errors : 
/Volumes/Extreme SSD/yolo-ios-app/YOLO/ViewController.swift:20:20: error: cannot find 'yolov8m' in scope
var mlModel = try! yolov8m(configuration: .init()).model
                   ^~~~~~~
/Volumes/Extreme SSD/yolo-ios-app/YOLO/ViewController.swift:20:44: error: cannot infer contextual base in reference to member 'init'
var mlModel = try! yolov8m(configuration: .init()).model. Any possibility to also run this on the iOS simulator?

**Comment by glenn-jocher** [comment]
@pascal-maker hello! It looks like you're encountering an issue with integrating a YOLOv8 model into an iOS project. Here are a few steps to troubleshoot and potentially resolve your issue:

1. **Check Model Availability**: Ensure that the `yolov8m` model is correctly added to your project. It should be in a format that is compatible with iOS (usually CoreML for Apple devices).

2. **Model Conversion**: If you have the model in a different format, you might need to convert it to CoreML. You can find guidance on model conversion in the Ultralytics Docs.

3. **Update Project Settings**: Make sure that the model file is included in your Xcode project's target membership so that it's bundled with your app.

4. **Code Syntax**: Double-check the syntax for initializing the model in Swift. It's possible there might be a typo or an issue with how the model is being instantiated.

5. **Simulator Limitations**: Running ML models on the iOS simulator can sometimes be problematic due to hardware acceleration limitations. If possible, try running your app on a physical device to see if the issue persists.

6. **Documentation and Examples**: For more detailed guidance and examples on integrating YOLO models with iOS, please refer to the Ultralytics Docs. While we don't have specific iOS integration examples, the general principles of working with YOLO models apply.

If you continue to face issues, please provide more details about the steps you've taken and any specific error messages you're seeing. The more information you provide, the better we can assist you. 😊

Remember, the YOLO community and the Ultralytics team are here to help. Good luck with your project!

**Comment by tonychanchen** [comment]
The mlprogram model format, deployable to iOS15, macOS12, watchOS8, tvOS15, and newer versions

**Comment by glenn-jocher** [comment]
@tonychanchen, thanks for the clarification regarding the `mlprogram` model format for deployment on iOS and other Apple platforms. Here are a few tailored suggestions:

1. **Model Format Compatibility**: Ensure your `yolov8m` model is correctly converted to the `.mlmodel` format, which can then be compiled into an `.mlprogram` for deployment. Apple's Core ML tools can be used for this conversion process.

2. **Xcode Integration**: After conversion, add the `.mlmodel` (which will automatically compile to `.mlprogram` when you build your project) to your Xcode project. Ensure it's correctly targeted and accessible in your Swift code.

3. **Code Update**: Given the error, it seems there might be an issue with how the model is being referenced in your Swift code. Ensure that the model name matches exactly, including case sensitivity, and that you're using the correct initializer syntax for an `MLModel`.

4. **Testing on Simulator vs. Device**: While `mlprogram` models are designed to work across iOS, macOS, watchOS, and tvOS, performance and compatibility can vary. If possible, test both on a physical device and the simulator. Note that the simulator might not fully emulate the hardware acceleration used by ML models.

5. **Documentation**: For the most current information on working with `.mlmodel` and `.mlprogram` formats, including deployment to various Apple platforms, please refer to the official Apple documentation and the Ultralytics Docs for any updates related to YOLO models.

6. **Debugging**: If the issue persists, consider enabling more verbose logging to pinpoint where the model loading fails. This can sometimes provide more insights into missing files, incorrect paths, or compatibility issues.

Remember, integrating advanced ML models into mobile and other platforms can be complex, and issues like these are not uncommon. Your persistence is key, and the community is here to support you. Keep experimenting, and don't hesitate to reach out with more details or questions. Good luck! 🚀

**Comment by john-rocky** [comment]
@pascal-maker 
Thank you for your question.
To use the app, get the mlpackage for Yolo11 n, s, m, l, x from the release notes, add it to the models directory of your project, and build it.
https://github.com/ultralytics/yolo-ios-app/releases
